// ─── Projects ────────────────────────────────────────────────────────────────

export const PROJECTS = [
  {
    icon: "🌿",
    title: "EcoTrack",
    desc: "Open-source carbon footprint calculator with real-time emission analysis and personal sustainability goals.",
    tags: ["React", "Node.js", "MongoDB"],
    category: "Open Source",
    stars: 2100,
    contributors: 14,
    status: "open",
    github: "https://github.com",
  },
  {
    icon: "🤖",
    title: "AutoGrade AI",
    desc: "ML-powered assignment grader that provides personalised feedback for educators across multiple subjects.",
    tags: ["Python", "TensorFlow", "FastAPI"],
    category: "AI/ML",
    stars: 870,
    contributors: 6,
    status: "active",
    github: "https://github.com",
  },
  {
    icon: "🗺️",
    title: "CampusNav",
    desc: "Indoor navigation app for large college campuses using BLE beacons and AR overlays.",
    tags: ["Flutter", "Dart", "Firebase"],
    category: "Mobile",
    stars: 540,
    contributors: 9,
    status: "active",
    github: "https://github.com",
  },
  {
    icon: "📊",
    title: "OpenBudget",
    desc: "Transparent public budget visualisation platform for local governments and institutions.",
    tags: ["Next.js", "D3.js", "PostgreSQL"],
    category: "Web",
    stars: 1200,
    contributors: 11,
    status: "open",
    github: "https://github.com",
  },
  {
    icon: "🔧",
    title: "DevLaunch CLI",
    desc: "Command-line scaffold tool that generates full-stack project structures with best-practice configs in seconds.",
    tags: ["TypeScript", "Bun", "YAML"],
    category: "DevTools",
    stars: 3300,
    contributors: 22,
    status: "active",
    github: "https://github.com",
  },
  {
    icon: "🧠",
    title: "MindMap AI",
    desc: "AI-enhanced collaborative mind-mapping tool with auto-layout, smart suggestions, and real-time co-editing.",
    tags: ["Vue 3", "OpenAI", "WebSockets"],
    category: "AI/ML",
    stars: 690,
    contributors: 5,
    status: "open",
    github: "https://github.com",
  },
  {
    icon: "🛒",
    title: "AgroLink",
    desc: "Marketplace connecting small-scale farmers directly with urban buyers, reducing middlemen costs by 40%.",
    tags: ["React Native", "Django", "AWS"],
    category: "Mobile",
    stars: 450,
    contributors: 8,
    status: "active",
    github: "https://github.com",
  },
  {
    icon: "📚",
    title: "PeerLearn",
    desc: "Peer-to-peer study session platform with smart scheduling, flashcards, and progress analytics.",
    tags: ["SvelteKit", "Supabase", "WebRTC"],
    category: "Web",
    stars: 980,
    contributors: 13,
    status: "open",
    github: "https://github.com",
  },
  {
    icon: "🔐",
    title: "SecureVault OSS",
    desc: "Zero-knowledge encrypted secrets manager for dev teams with CLI and browser extension.",
    tags: ["Rust", "WebAssembly", "AES-256"],
    category: "Open Source",
    stars: 1750,
    contributors: 18,
    status: "active",
    github: "https://github.com",
  },
  {
    icon: "📡",
    title: "NetSim",
    desc: "Interactive network topology simulator for students learning distributed systems and routing algorithms.",
    tags: ["Electron", "Three.js", "Python"],
    category: "DevTools",
    stars: 620,
    contributors: 7,
    status: "open",
    github: "https://github.com",
  },
  {
    icon: "🎓",
    title: "ScholarsAI",
    desc: "AI college application assistant that helps students shortlist universities based on profile fit and aid.",
    tags: ["LangChain", "Pinecone", "React"],
    category: "AI/ML",
    stars: 1100,
    contributors: 4,
    status: "active",
    github: "https://github.com",
  },
  {
    icon: "🌐",
    title: "LocalFirst CMS",
    desc: "Fully offline-capable CMS for rural NGOs that syncs when connectivity is restored.",
    tags: ["CouchDB", "PouchDB", "PWA"],
    category: "Open Source",
    stars: 390,
    contributors: 6,
    status: "open",
    github: "https://github.com",
  },
];

// ─── Events ──────────────────────────────────────────────────────────────────

export const EVENTS = [
  {
    month: "Apr", day: "12",
    title: "HackSphere 2026",
    org: "IIT Madras × Devsphere",
    type: "Hackathon", location: "Chennai", mode: "Hybrid",
    prize: "₹5,00,000", spots: "320 spots left", upcoming: true,
  },
  {
    month: "Apr", day: "18",
    title: "AI/ML Workshop: Building RAG Systems",
    org: "Anna University Dev Club",
    type: "Workshop", location: "Chennai", mode: "Online",
    prize: null, spots: "80 spots left", upcoming: true,
  },
  {
    month: "Apr", day: "26",
    title: "Open Source Sprint Weekend",
    org: "Devsphere Chennai Chapter",
    type: "Hackathon", location: "SRMIST Campus", mode: "In-person",
    prize: "₹50,000", spots: "Unlimited", upcoming: true,
  },
  {
    month: "May", day: "3",
    title: "Frontend Fundamentals Bootcamp",
    org: "VIT Vellore Tech Club",
    type: "Workshop", location: "Vellore", mode: "In-person",
    prize: null, spots: "50 seats", upcoming: true,
  },
  {
    month: "May", day: "10",
    title: "National Coding League — Round 2",
    org: "CodeIndia Foundation",
    type: "Competition", location: "Pan-India", mode: "Online",
    prize: "₹2,00,000", spots: "Open registration", upcoming: true,
  },
  {
    month: "May", day: "17",
    title: "Cloud & DevOps Deep Dive",
    org: "AWS User Group Chennai",
    type: "Webinar", location: "Online", mode: "Online",
    prize: null, spots: "500 capacity", upcoming: true,
  },
  {
    month: "Mar", day: "22",
    title: "Smart India Hackathon — Regional",
    org: "Government of India",
    type: "Hackathon", location: "Various Venues", mode: "In-person",
    prize: "₹10,00,000", spots: "Concluded", upcoming: false,
  },
  {
    month: "Mar", day: "8",
    title: "Women in Tech Summit 2026",
    org: "Devsphere × GirlScript",
    type: "Webinar", location: "Online", mode: "Online",
    prize: null, spots: "2,400 attended", upcoming: false,
  },
  {
    month: "Feb", day: "28",
    title: "Blockchain & Web3 Hackathon",
    org: "NIT Trichy Block Club",
    type: "Hackathon", location: "Trichy", mode: "Hybrid",
    prize: "₹3,00,000", spots: "120 teams participated", upcoming: false,
  },
  {
    month: "Feb", day: "14",
    title: "Design × Dev: UX for Engineers",
    org: "UX Chennai Collective",
    type: "Workshop", location: "Chennai", mode: "In-person",
    prize: null, spots: "90 attended", upcoming: false,
  },
];

// ─── Community Builds ─────────────────────────────────────────────────────────

export const COMMUNITY_BUILDS = [
  {
    month: "April 2026",
    icon: "🌿",
    title: "EcoTrack",
    desc: "An open-source carbon footprint calculator built collaboratively by 14 contributors across 6 colleges. Features real-time emission tracking, goal setting, and a public leaderboard.",
    tags: ["React", "Node.js", "MongoDB", "Chart.js"],
    contributors: 14,
    colleges: 6,
    stars: 2100,
    featured: true,
    demo: "https://github.com",
    github: "https://github.com",
  },
  {
    month: "March 2026",
    icon: "🗳️",
    title: "VoteChain",
    desc: "A blockchain-based transparent voting system for college student elections. Immutable records, anonymous ballots, and real-time result dashboards.",
    tags: ["Solidity", "Hardhat", "React", "ethers.js"],
    contributors: 10,
    colleges: 4,
    stars: 890,
    featured: false,
    demo: "https://github.com",
    github: "https://github.com",
  },
  {
    month: "February 2026",
    icon: "🩺",
    title: "MedBridge",
    desc: "Connects rural patients with urban doctors via low-bandwidth video consultations. Includes offline symptom checker and medicine reminder system.",
    tags: ["Flutter", "WebRTC", "Firebase", "TensorFlow Lite"],
    contributors: 12,
    colleges: 5,
    stars: 1340,
    featured: false,
    demo: "https://github.com",
    github: "https://github.com",
  },
  {
    month: "January 2026",
    icon: "♻️",
    title: "WasteWise",
    desc: "AI-powered waste segregation guide using your phone camera. Identifies waste type and shows nearest recycling drop points on a live map.",
    tags: ["React Native", "TensorFlow.js", "Google Maps API"],
    contributors: 8,
    colleges: 3,
    stars: 670,
    featured: false,
    demo: "https://github.com",
    github: "https://github.com",
  },
  {
    month: "December 2025",
    icon: "📖",
    title: "OpenLib",
    desc: "A peer-to-peer digital library where students share notes, books, and study resources. Full-text search, ratings, and subject-based collections.",
    tags: ["Next.js", "Algolia", "Supabase", "Cloudinary"],
    contributors: 9,
    colleges: 7,
    stars: 1020,
    featured: false,
    demo: "https://github.com",
    github: "https://github.com",
  },
  {
    month: "November 2025",
    icon: "🚌",
    title: "BusNow",
    desc: "Real-time college bus tracking app with live location sharing by drivers, ETA notifications, and crowd density indicators.",
    tags: ["React Native", "Socket.io", "Express", "Redis"],
    contributors: 7,
    colleges: 2,
    stars: 530,
    featured: false,
    demo: "https://github.com",
    github: "https://github.com",
  },
];
